spring.application.name=bookstore

spring.jpa.show-sql=true
#kertoo, mistä löytyy HAL formaatissa olevat REST palvelut
spring.data.rest.base-path=/rest

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/backend_s26
spring.datasource.username=postgres
spring.datasource.password=root

#JPA/hibernate ei tee muutoksia ulkoiseen kantaan none arvolla
spring.jpa.hibernate.ddl-auto=none