spring.application.name=bookstore

#kertoo, mistä löytyy HAL formaatissa olevat REST palvelut
spring.data.rest.base-path=/rest

#spring.h2.console.enabled=true
spring.jpa.show-sql=true
#spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

