spring.application.name=bookstore

spring.jpa.show-sql=true
spring.data.rest.base-path=/api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


#none: ei tee mitään skeeman suhteen.Sovellus olettaa, että skeema on jo olemassa.
#validate: varmistaa, että tietokannan skeema vastaa entiteettejä. Jos eroavaisuuksia löytyy, sovellus ei käynnisty.
#update: päivittää skeeman entiteettien mukaiseksi. Säilyttää olemassa olevat tiedot. Hyvä kehityksessä, ei suositeltu tuotannossa.
#create: luo skeeman uudelleen joka käynnistyksellä. Poistaa vanhat tiedot.
#create-drop: luo skeeman sovelluksen käynnistyessä ja poistaa sen sovelluksen sammuessa.
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update